# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f6da881cf3f1e07991d86e5711b81982"
name = "app"
handle = "app-1121"
application_url = "https://meter-trauma-steal-denmark.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sabs-testify-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://meter-trauma-steal-denmark.trycloudflare.com/auth/callback",
  "https://meter-trauma-steal-denmark.trycloudflare.com/auth/shopify/callback",
  "https://meter-trauma-steal-denmark.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
